### ISSUE TITLE
License expired

### ISSUE THREAD

**Issue by FyR0z** [maliceio/malice-bitdefender#1]
Hello license expire how we can set our own ?

**Comment by blacktop** [comment]
Is it still expired?  Its crazy how if you walk away from something for a few months your brain garbage collects all that stuff 🤣 I rebuilt it and the tests pass so I think that it should be good to go?

To use your own license you would build the docker image by doing a `make build` with the key file in the root dir.  The builder looks for the file `bd.key` and adds it.  Which makes me think I had a key at some point.  

Need to boot up some old computers and find it haha

Another thing you could do is map your own `bdscan.conf` on top of mine like so:
```
docker run -v `pwd`/bdscan.conf:/opt/BitDefender-scanner/etc/bdscan.conf malice/bitdefender
```
in the conf file you replace the trial `Key` with your key.

**Comment by mandb** [comment]
Looks like bitdefender will generate a new 30-day evaluation key every time the container is built, solution is pretty simple for those looking to test:

```
mkdir bddocker
cd bddocker/
git clone https://github.com/malice-plugins/bitdefender.git .
docker build -t malice/bitdefender .
```

you will eventually see: 

```
Step 19/24 : RUN mkdir -p /opt/malice && echo "accept" | bdscan --update
 ---> Running in 9d8018dbb5ea
BitDefender Antivirus Scanner for Unices v7.141118 Linux-amd64
Copyright (C) 1996-2014 BitDefender. All rights reserved.
Trial key found. 30 days remaining.
```

Free to evaluate for 30 days.   

Only suggestion would be:

Make avscan service aware of output suggesting the license is expired,  Submitting via web interface with an expired license will cause container to die with no verbosity.  Additionally, the scanner will simply report no viruses when run from malice cli.

Same thing happens with f-secure.
