### ISSUE TITLE
Today doesn't work

### ISSUE THREAD

**Issue by theRedCount** [maliceio/malice-bitdefender#2]
I used it for some days.
Today it not work properly.

```
$ sudo docker run --rm malice/bitdefender EICAR
time="2019-02-05T10:28:07Z" level=fatal msg="exit status 254" category=av path=/malware/EICAR plugin=bitdefender
```

**Comment by blacktop** [comment]
So I just rebuilt the plugin and it seems to be working for me?

Can you re-pull the plugin in a few hours (once it's done building in the dockerHUB) and try again?

**Comment by theRedCount** [comment]
Today I have removed the docker image and retry...
Now work. Thanks a lot!
